import { jsPDF } from 'jspdf';
import { format } from 'date-fns';

export function generateRenewalPDF(businessProfile, licenseType, formData) {
  const doc = new jsPDF();
  const today = format(new Date(), 'dd MMM yyyy');

  // Header
  doc.setFillColor(13, 27, 42);
  doc.rect(0, 0, 210, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('⚡ ComplianceAI', 15, 18);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`${licenseType} Renewal Form`, 15, 28);

  // Business details
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Business Information', 15, 50);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  const bizFields = [
    ['Business Name', businessProfile?.business_name],
    ['Owner Name', businessProfile?.owner_name],
    ['Phone', businessProfile?.phone],
    ['Address', businessProfile?.address],
    ['City', businessProfile?.city],
    ['GSTIN', businessProfile?.gstin],
  ];

  let y = 60;
  bizFields.forEach(([label, value]) => {
    if (value) {
      doc.setFont('helvetica', 'bold');
      doc.text(`${label}:`, 15, y);
      doc.setFont('helvetica', 'normal');
      doc.text(value, 70, y);
      y += 8;
    }
  });

  // Form fields
  if (formData?.formFields?.length) {
    y += 5;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Form Fields', 15, y);
    y += 10;
    doc.setFontSize(10);
    formData.formFields.forEach((field) => {
      doc.setFont('helvetica', 'bold');
      doc.text(`${field.fieldName}:`, 15, y);
      doc.setFont('helvetica', 'normal');
      doc.text(field.fieldValue || '________________', 80, y);
      y += 8;
      if (y > 270) { doc.addPage(); y = 20; }
    });
  }

  // Document checklist
  if (formData?.documentChecklist?.length) {
    y += 5;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Document Checklist', 15, y);
    y += 10;
    doc.setFontSize(10);
    formData.documentChecklist.forEach((item) => {
      doc.text(`☐  ${item}`, 15, y);
      y += 8;
      if (y > 270) { doc.addPage(); y = 20; }
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by ComplianceAI on ${today}`, 15, 285);

  return doc.output('bloburl');
}
