import { differenceInDays, addDays, subDays, format } from 'date-fns';

const today = new Date();

export const DEMO_BUSINESS = {
  id: 'demo-001',
  business_name: 'Spice Garden Restaurant',
  business_type: 'restaurant',
  owner_name: 'Rajesh Kumar',
  phone: '+91 98765 43210',
  email: 'rajesh@spicegarden.in',
  address: '12, Indiranagar 100 Feet Road',
  city: 'Bengaluru',
  state: 'Karnataka',
  gstin: '29AABCS1429B1Z1',
  compliance_score: 0,
};

export const DEMO_LICENSES = [
  {
    id: 'demo-lic-001',
    business_id: 'demo-001',
    license_type: 'FSSAI',
    license_number: 'FSSAI-2021-KA-0049821',
    issuing_authority: 'Food Safety and Standards Authority of India',
    issue_date: format(subDays(today, 377), 'yyyy-MM-dd'),
    expiry_date: format(subDays(today, 12), 'yyyy-MM-dd'),
    status: 'expired',
    document_url: null,
    confidence_score: 94,
    renewal_portal_url: 'https://foscos.fssai.gov.in',
  },
  {
    id: 'demo-lic-002',
    business_id: 'demo-001',
    license_type: 'FIRE_NOC',
    license_number: 'KSFE/BLR/2023/00441',
    issuing_authority: 'Karnataka State Fire and Emergency Services',
    issue_date: format(subDays(today, 357), 'yyyy-MM-dd'),
    expiry_date: format(addDays(today, 8), 'yyyy-MM-dd'),
    status: 'expiring',
    document_url: null,
    confidence_score: 88,
    renewal_portal_url: 'https://ksfe.karnataka.gov.in',
  },
  {
    id: 'demo-lic-003',
    business_id: 'demo-001',
    license_type: 'TRADE_LICENSE',
    license_number: 'BBMP/TL/IND/2023/88321',
    issuing_authority: 'BBMP (Bruhat Bengaluru Mahanagara Palike)',
    issue_date: format(subDays(today, 342), 'yyyy-MM-dd'),
    expiry_date: format(addDays(today, 23), 'yyyy-MM-dd'),
    status: 'expiring',
    document_url: null,
    confidence_score: 91,
    renewal_portal_url: 'https://bbmptax.karnataka.gov.in',
  },
  {
    id: 'demo-lic-004',
    business_id: 'demo-001',
    license_type: 'SHOP_ESTABLISHMENT',
    license_number: 'KA-LAB/SE/2023/40129',
    issuing_authority: 'Karnataka Labour Department',
    issue_date: format(subDays(today, 313), 'yyyy-MM-dd'),
    expiry_date: format(addDays(today, 52), 'yyyy-MM-dd'),
    status: 'expiring',
    document_url: null,
    confidence_score: 85,
    renewal_portal_url: 'https://labour.karnataka.gov.in',
  },
  {
    id: 'demo-lic-005',
    business_id: 'demo-001',
    license_type: 'GST',
    license_number: '29AABCS1429B1Z1',
    issuing_authority: 'GST Council of India',
    issue_date: format(subDays(today, 480), 'yyyy-MM-dd'),
    expiry_date: format(addDays(today, 240), 'yyyy-MM-dd'),
    status: 'active',
    document_url: null,
    confidence_score: 98,
    renewal_portal_url: 'https://www.gst.gov.in',
  },
  {
    id: 'demo-lic-006',
    business_id: 'demo-001',
    license_type: 'EATING_HOUSE',
    license_number: 'BCP/EH/IND/2023/11042',
    issuing_authority: 'Bengaluru City Police',
    issue_date: format(subDays(today, 185), 'yyyy-MM-dd'),
    expiry_date: format(addDays(today, 180), 'yyyy-MM-dd'),
    status: 'active',
    document_url: null,
    confidence_score: 79,
    renewal_portal_url: 'https://bengalurupolice.karnataka.gov.in',
  },
];
